GenesisV2/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.sitemaps.views import sitemap
from apps.front.sitemap import PageSitemap
from django.conf import settings
sitemaps = {
    'page': PageSitemap,
}
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('dashboard/').strip(), include('apps.dashboard.urls'), name='dashboard'),
    path(_('dashboard/configuratie/').strip(), include('apps.conf.urls'), name='configuration'),
    path(_('dashboard/gebruiker/').strip(), include('apps.user.urls'), name='user'),
    path(_('dashboard/modules/').strip(), include('apps.modules.urls'), name='modules'),
    path(_('dashboard/translations/').strip(), include('apps.translation.urls'), name='translation'),
    path(_('dashboard/pages/').strip(), include('apps.pages.urls'), name='pages'),
    path(_('dashboard/blocks/').strip(), include('apps.blocks.urls'), name='blocks'),
    path(_('dashboard/history/').strip(), include('apps.history.urls'), name='history'),
    path(_('dashboard/news/').strip(), include('apps.news.urls'), name='news'),
    path(_('dashboard/base/').strip(), include('apps.base.urls'), name='base'),
    path(_('dashboard/media/').strip(), include('apps.filemanager.urls'), name='filemanager'),
    path(_('dashboard/mail/').strip(), include('apps.mail.urls'), name='mail'),
    path(_('dashboard/formbuilder/').strip(), include('apps.formbuilder.urls'), name='form'),
    path(_('dashboard/logs/').strip(), include('apps.logs.urls'), name='logs'),
    path(_('dashboard/data/').strip(), include('apps.data.urls'), name='data'),
    path(_('dashboard/search/').strip(), include('apps.search.urls'), name='search'),
    path(_('account/').strip(), include('apps.user.account_urls'), name='user_dashboard'),

    path('', include('apps.front.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap'),
    prefix_default_language=False
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        
handler404 = 'apps.front.views.handler404'

handler500 = 'apps.front.views.handler500'

apps/conf/urls.py
from django.conf.urls import url
from django.urls import path, include
from apps.conf.views import overview_conf, add_conf, edit_conf, delete_conf, delete_ajax_conf_modal, save_conf
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    url(_('^overview/$').strip(),overview_conf,name="overviewconf"),
    url(_('^add$').strip(),add_conf,name="addconf"),
    url(_('^save$').strip(),save_conf,name="saveconf"),
    url(_('^edit/(?P<pk>[0-9a-f-]+)$').strip(),edit_conf,name="editconf"),
    url(_('^delete/(?P<pk>[0-9a-f-]+)$').strip(),delete_conf,name="deleteconf"),
    url(_('^delete/modal$').strip(),delete_ajax_conf_modal,name="deletemodalconf"),
]

apps/mail/urls.py
from django.conf.urls import url
from .views import delete_ajax_mailtemplate_modal, overview_mailtemplate, add_mailtemplate, edit_mailtemplate, delete_mailtemplate, \
                   overview_email, toggle_mailtemplate_activation_view, \
                   get_version_ajax_modal, select_version, \
                   delete_version, add_version_comment, get_delete_version_ajax_modal, \
                   overview_reversion, revert_mail_item
from django.utils.translation import ugettext as _

urlpatterns = [
    url(_('^mailtemplate/overview$').strip(),overview_mailtemplate,name="overviewmailtemplate"),
    url(_('^mailtemplate/add$').strip(),add_mailtemplate,name="addmailtemplate"),
    url(_('^mailtemplate/toggle-activation/(?P<pk>[0-9a-f-]+)$').strip(), toggle_mailtemplate_activation_view, name="activate-mailtemplates"),
    url(_('^mailtemplate/edit/(?P<pk>[0-9a-f-]+)$').strip(),edit_mailtemplate,name="editmailtemplate"),
    url(_('^mailtemplate/delete/(?P<pk>[0-9a-f-]+)$').strip(),delete_mailtemplate,name="deletemailtemplate"),
    url(_('^mailtemplate/delete/modal$').strip(),delete_ajax_mailtemplate_modal,name="deletemodalmailtemplate"),

    url(_('^overview$').strip(),overview_email,name="overviewemail"),

    url(_('^overview/reversion/(?P<mode>[a-z]+)/$').strip(),overview_reversion,name="overviewreversionmail"),
    url(_('^revert/(?P<mode>[a-z]+)/(?P<pk>[0-9a-f-]+)/$').strip(),revert_mail_item,name="revertmail"),

    url(_('^version/modal/template/$').strip(),get_version_ajax_modal,name="mailtemplateversionmodal"),
    url(_('^version/modal/delete/(?P<mode>[a-z]+)/$').strip(),get_delete_version_ajax_modal,name="maildeleteversionmodal"),
    url(_('^version/(?P<mode>[a-z]+)/(?P<pk>[0-9a-f-]+)$').strip(),select_version,name="mailselectversion"),
    url(_('^version/delete/(?P<mode>[a-z]+)/(?P<pk>[0-9a-f-]+)/$').strip(),delete_version,name="maildeleteversion"),
    url(_('^version/comment/(?P<mode>[a-z]+)/(?P<pk>[0-9a-f-]+)/$').strip(),add_version_comment,name="mailaddversioncomment"),
]

apps/conf/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
import uuid

# Create your models here.
class Configuration(models.Model):
    USER_MODEL = 'user'
    CLIENT_MODEL = 'client'
    GENERAL_MODEL = 'general'
    SCHEMA_MODEL = 'schema'
    MAIL_MODEL = 'mail'

    
    AVAILABLE_MODELS = (
        (USER_MODEL, _('Gebruiker')),
        (CLIENT_MODEL, _('Klant')),
        (GENERAL_MODEL, _('Algemeen')),
        (SCHEMA_MODEL, _('Schema Markup')),
        (MAIL_MODEL, _('Mail'))
    )

    TYPE_TEXT = 'text'
    TYPE_BOOLEAN = 'boolean'

    TYPES = [
        (TYPE_TEXT, _('Textvalue')),
        (TYPE_BOOLEAN , _('Booleanvalue')),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    key_name = models.CharField(unique=True, max_length=255)
    title = models.CharField(max_length=255)
    value = models.CharField(null=True, blank=True, max_length=255)
    description = models.TextField(null=True, blank=True)
    conf_type = models.CharField(choices=AVAILABLE_MODELS, default=USER_MODEL, max_length=100)
    type = models.CharField(max_length=22, choices=TYPES, default=TYPE_TEXT)

    class Meta:
        verbose_name = _('Configuration')

    def __str__(self):
        return self.value


apps/conf/forms.py
from django.forms import ModelForm
from apps.conf.models import Configuration

class ConfigurationValueForm(ModelForm):
    class Meta:
        model = Configuration
        fields = ['value']

class ConfigurationForm(ModelForm):
    class Meta:
        model = Configuration
        fields = ['value','key_name', 'title', 'description', 'conf_type', 'type']

apps/conf/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView
from django.contrib.admin.views.decorators import staff_member_required
from apps.base.utils import has_perms
from django.contrib import messages
from apps.conf.models import Configuration
from apps.conf.forms import ConfigurationForm
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string
from django.http import JsonResponse
# Create your views here.

@staff_member_required(login_url=reverse_lazy('login'))
def overview_conf(request):
    conf = Configuration.objects.filter()
    sort_by = request.GET.get('sort_by')
    if sort_by and (sort_by in [f.name for f in Configuration._meta.fields]):
        if sort_by:
            conf = conf.order_by(sort_by)
    has_perms(request, ["conf.add_configuration"], 'conf/index.html')
    context = {
        "conf":conf,
    }
    return render(request,'conf/index.html', context)

@staff_member_required(login_url=reverse_lazy('login'))
def add_conf(request):
    has_perms(request, ["conf.add_configuration"], None, 'overviewconf')
    if request.method == 'POST':
        form = ConfigurationForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()

            messages.add_message(request, messages.SUCCESS, _('The configuration has been succesfully added!'))

            return redirect('overviewconf')
    else:
        form = ConfigurationForm()

    return render(request, 'conf/add.html', {
        'form': form,
    })

@staff_member_required(login_url=reverse_lazy('login'))
def edit_conf(request, pk):
    has_perms(request, ["conf.change_configuration"], None, 'overviewconf')
    instance = get_object_or_404(Configuration, pk=pk)
    if request.method == 'POST':
        form = ConfigurationForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()
            messages.add_message(request, messages.SUCCESS, _('The configuration has been succesfully changed!'))

            return redirect('overviewconf')
    else:
        form = ConfigurationForm(instance=instance)

    return render(request, 'conf/edit.html', {
        'form': form,
        'conf':instance
    })

def save_conf(request):
    has_perms(request, ["conf.change_configuration"], None, 'overviewconf')
    conf = Configuration.objects.filter()
    if request.method == "POST":
        values = request.POST.getlist('conf-value')
        count = 0
        for item in conf:
            item.value = values[count]
            item.save()
            count += 1
    return redirect('overviewconf')

@staff_member_required(login_url=reverse_lazy('login'))
def delete_ajax_conf_modal(request):
    if request.is_ajax():
        data = {}
        id = request.POST.get('id', False)
        conf = Configuration.objects.get(id=id)
        if conf:
            context = {
                'conf': conf
            }
            data = {
                'template': render_to_string('conf/__partials/modal.html', context=context, request=request)
            }
        return JsonResponse(data)
    return False

        
@staff_member_required(login_url=reverse_lazy('login'))
def delete_conf(request,pk):
    has_perms(request, ["conf.delete_configuration"], None, 'overviewconf')
    instance = Configuration.objects.get(pk=pk)
    instance.delete()
    messages.add_message(request, messages.SUCCESS, _('The configuration has been succesfully deleted!'))
    return redirect('overviewconf')
        


apps/conf/templates/conf/__form.html
{% load i18n %}
    {% csrf_token %}
    <div class="widget-content widget-content-area rounded-pills-icon">
        
        <ul class="nav nav-pills mb-4 mt-3  justify-content-center" id="rounded-pills-icon-tab" role="tablist">
            <li class="nav-item ml-2 mr-2">
                <a class="nav-link mb-2 text-center active" id="rounded-pills-icon-profile-tab" data-toggle="pill" href="#rounded-pills-icon-profile" role="tab" aria-controls="rounded-pills-icon-profile" aria-selected="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
                    {% trans 'Configuration' %}
                    <span class="tab-error-indicator badge btn-danger"></span>
                </a>
            </li>
        </ul>
        {{ form.non_field_errors }}
        <div class="tab-content" id="rounded-pills-icon-tabContent">
            <div class="tab-pane fade active show" id="rounded-pills-icon-profile" role="tabpanel" aria-labelledby="rounded-pills-icon-profile-tab">
                {% include 'conf/__partials/__conf.html' %}
            </div>
        </div>
    </div>
    <div class="col-md-12 text-right mb-5">
        <button class="btn btn-success mb-2 mr-2" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-save"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg> {% trans 'Save' %}</button>
        <a href="{% url 'overviewconf' %}" class="btn btn-danger mb-2 mr-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x-square"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="9" x2="15" y2="15"></line><line x1="15" y1="9" x2="9" y2="15"></line></svg> {% trans 'Cancel' %}</a>
    </div>

apps/conf/templates/conf/add.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
<!--  BEGIN CONTENT AREA  -->
<div id="content" class="main-content">
    <div class="row layout-top-spacing">
        <div id="tabsWithIcons" class="col-lg-12 col-12 layout-spacing">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{% trans 'Add configuration' %}</h4>
                        </div>
                    </div>
                </div>
                <form class="form" action="{% url 'addconf' %}" name="form" method="post" enctype='multipart/form-data'>
                    {% include 'conf/__form.html' %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script type="text/javascript">
    $('.tab-pane').each(function () {
        var tab = $(this);
        if (tab.find('.form-control.is-invalid').length > 0) {
            $('[data-toggle="pill"][href="#' + tab.attr('id') + '"]').find('.tab-error-indicator').html(tab.find('.form-control.is-invalid').length);
        }
    });
</script>
{% endblock %}

apps/conf/templates/conf/edit.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% block content %}
<!--  BEGIN CONTENT AREA  -->
<div id="content" class="main-content">
    <div class="row layout-top-spacing">
        <div id="tabsWithIcons" class="col-lg-12 col-12 layout-spacing">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{% trans 'Edit configuration' %}</h4>
                        </div>
                    </div>
                </div>
                <form class="form" action="{% url 'editconf' conf.pk %}" name="form" method="post" enctype='multipart/form-data'>
                    {% include 'conf/__form.html' %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block js %}
<script type="text/javascript">
    $('.tab-pane').each(function () {
        var tab = $(this);
        if (tab.find('.form-control.is-invalid').length > 0) {
            $('[data-toggle="pill"][href="#' + tab.attr('id') + '"]').find('.tab-error-indicator').html(tab.find('.form-control.is-invalid').length);
        }
    });
</script>
{% endblock %}

apps/conf/templates/conf/index.html
{% extends 'dashboard/base.html' %}
{% load static i18n svg %}
{% block content %}
<div class="row layout-top-spacing layout-spacing">
    <div class="col-lg-12">
        <div class="statbox widget box box-shadow">
            <form method="POST" action="{% url 'saveconf' %}">
                {% csrf_token %} 
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>{% trans 'Configuration overview' %}</h4>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'addconf' %}" class="btn btn-info mb-2 ml-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg> {% trans 'Add configuration' %}</a>
                            {% endif %}
                            <button type="submit" class="btn btn-success mb-2 ml-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-save"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg> {% trans 'Save' %}</button>

                            <div class="form-group col-md-3"
                                style="display: inline-block;">
                                  <!-- <label for="inputState">State</label> -->
                                  <select name="sort_by" class="form-control sort-conf-field">
                                    <option selected>Sort by</option>
                                    <option value="type">Type</option>
                                    <option value="conf_type">Category</option>
                                  </select>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">
                    <div class="table-responsive mb-4">
                        <table id="style-3" class="table style-3  table-hover">
                            <thead>
                                <tr>
                                    <th>{% trans 'Title' %}</th>
                                    <th>{% trans 'Type' %}</th>
                                    <th>{% trans 'Description' %}</th>
                                    <th>{% trans 'Value' %}</th>
                                    {% if request.user.is_superuser %}
                                        <th class="text-center">{% trans 'Action' %}</th>
                                    {% endif %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in conf %}
                                    <tr>
                                        <td>{{item.title}}</td>
                                        <td>{{item.get_conf_type_display}}</td>
                                        <td>{{item.description}}</td>
                                        <td><input type="text" class="form-control" name="conf-value" id="conf-value" value="{{item.value}}"></td>
                                        {% if request.user.is_superuser %}
                                            <td class="text-center">
                                                {% include 'conf/__partials/actions.html' with item=item %}
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}  
                            </tbody>
                        </table>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal-placeholder">

    </div>
</div>
{% endblock content %}
{% block js %}
<script>
    $('.open-delete-modal').on('click', function() {
        var id = $(this).data('id');
        $.ajax({
            url: '{% url 'deletemodalconf'  %}',
            type:"POST",
            data: {
                'id': id,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            success:function(data){
                $('.modal-placeholder').html(data.template);
                $('.modal').modal();
            }
        });
    })

    $('.sort-conf-field').change(function(e){
        let value = $(this).val();
        let url = "{% url 'overviewconf'  %}";
        window.location = `${url}?sort_by=${value}`

    });
</script>
{% endblock %}